INSERT INTO giftlist_users (id, username, name, password) VALUES
(1, 'Dee','Danielle','$2a$12$TNjdWXBhzjBkX0ZutpZ92ermr6kBG55tmu9ZdAshuFdCsaSWsqfs6'),
(2, 'Mike','Michael','$2a$12$TNjdWXBhzjBkX0ZutpZ92ermr6kBG55tmu9ZdAshuFdCsaSWsqfs6'),
(3, 'Ash','Ashley','$2a$12$TNjdWXBhzjBkX0ZutpZ92ermr6kBG55tmu9ZdAshuFdCsaSWsqfs6'),
(4, 'Steph','Stephanie','$2a$12$TNjdWXBhzjBkX0ZutpZ92ermr6kBG55tmu9ZdAshuFdCsaSWsqfs6'),
(5, 'Hal','Haley','$2a$12$TNjdWXBhzjBkX0ZutpZ92ermr6kBG55tmu9ZdAshuFdCsaSWsqfs6'),
(6, 'RJ','Ryan','$2a$12$TNjdWXBhzjBkX0ZutpZ92ermr6kBG55tmu9ZdAshuFdCsaSWsqfs6'),
(7, 'Pat','Patrick','$2a$12$TNjdWXBhzjBkX0ZutpZ92ermr6kBG55tmu9ZdAshuFdCsaSWsqfs6');
  
INSERT INTO giftlist_lists (listname, user_id)
VALUES
('Dees Christmas List', 1),
('Mikes Christmas List', 2),
('Ashs Christmas List', 3),
('Stephs Christmas List', 4),
('Hals Christmas List', 5),
('RJs Christmas List', 6),
('Pats Christmas List', 7);

INSERT INTO giftlist_items (name, list_id)
VALUES
('Apple TV', 1),
('iPad', 1),
('Perfume', 1),
('Slippers', 1),
('Yeti Mug', 1),
('iPad', 2),
('Xbox games', 2),
('Portable phone charger', 2),
('Leather wallet', 2),
('Slippers', 2),
('Slippers', 3),
('iPhone case', 3),
('Fleece Pajamas', 3),
('Nespresso Coffee Maker', 3),
('Winter Boots', 3),
('iPad', 4),
('Heated Blanket',4),
('Running Shoes', 4),
('Air Fryer', 4),
('Headphones', 4),
('Gold necklace', 5),
('Sweater', 5),
('Purse', 5),
('Perfume', 5),
('Yeti Mug', 5),
('iPhone', 6),
('Leather wallet', 6),
('Slippers', 6),
('Winter Coat', 6),
('Nintendo Switch', 6),
('Luggage', 7),
('Cologne', 7),
('Slippers',7),
('Yeti Mug', 7),
('Automatic Car Starter', 7);
